import 'package:flutter/material.dart';

const kBackGroundColor = Color(0xFFEEDB63);
const kGreenTextColor = Color(0xFF008037);
const kPurpleColor = Color(0xFF5E17EB);

const kMainPageButtonTextStyle = TextStyle(
  fontWeight: FontWeight.w500,
  fontSize: 36,
  color: kGreenTextColor,
);

final kScreenPagesAppBar = AppBar(
  centerTitle: true,
  backgroundColor: kBackGroundColor,
  title: Image.asset(
    'images/appBar.png',
    height: 70,
    width: 1000,
  ),
);

const kExpandablePanelTextStyle1 = TextStyle(
  fontSize: 20,
  fontWeight: FontWeight.bold,
);

List<String> yasListHeader = [
  '1.Yaş',
  '2.Yaş',
  '3.Yaş',
  '4.Yaş',
  '5.Yaş',
  'Kaynakça'
];
List<String> yasList = [
  '\nZihinsel gelişim, doğumdan önce başlar ve çocuğun çevresindekilerle kurduğu iletişime ve etrafındaki uyarıcılara bağlıdır. Çocuk doğduğu andan itibaren çevresinin farkındadır ve onu keşfetmek ister. Erkenden görülen bu keşif ihtiyacı çocuğun bir yaş civarında yürümeye başlamasıyla hızlanır. Çocuk etrafta gezdikçe, etrafındaki insan ve nesnelerle oynadıkça kendi bedenini, evini, dış dünyayı, çevresindeki ilişkileri ve kuralları kavrar. Bir yaşını bitirdiğinde, çocuğun zihinsel becerileri birden artmış gibidir. Sürekli gözlemleyen çocuk, çok çabuk öğrenir ve öğrendiklerini yansıtır. Bu yaşta alıcı dili gelişmiş olan çocuk artık kendisine söylenenleri anlayabilir. Anne bir oyuncağı kendisine getirmesini söylediğinde çocuk bu komutu anlar ve yerine getirir veya komutu yerine getirmeyi reddeder ancak tepkilerinden anneyi anladığı görülür. Bir yaşındaki çocuk artık “sen” ve “ben” ayrımını bilir. Kendi özgürlüğünün ve bireyselliğinin farkına vardığından “Hayır” en sık kullandığı cevap haline gelir. Bu şekilde çocuk kendi kararlarını vermeye ve sınırlarını keşfetmeye başlar. Etrafındaki konuşmaları ve kelimeleri anlayan çocuk, bu konuşmaları dikkatle dinler ve dilin kurallarını öğrenir, kelimeleri taklit etmeye başlar. “Anne”, “Baba”, “Mama” gibi birkaç basit kelimeyi doğru kişilere, doğru zamanlarda söyleyebilen çocuk, konuşmaya hazırlanır. Bu dönemde çocuğun çıkardığı bazı sesler ve kelimeler anlaşılmayabilir. Burada anne babadan beklenen: çocuğun doğru telaffuz edemediği ses veya kelimeyi düzgün bir şekilde tekrar etmesi, doğrusunu çocuğa duyurmasıdır. Konuşmayı öğrenen çocuğun çabası takdir edilmeli, konuşması ilgi ile izlenmeli, kendisi ile diyalog kurulmalı, konuşması teşvik edilmelidir, anne baba ve çevrenin bu tepkileri, çocuğun konuşma çabasını arttırır. Dil gelişiminin yanında çocuğun beden dili de gelişir. Çocuk el kol hareketlerini, gözlerini ve yüz mimiklerini kendini doğru bir şekilde ifade etmek için kullanabilir.',
  '\nKendi kimliğine ilişkin giderek artan bir farkındalığa ulaşmaları, 2 yaş dolaylarındaki çocukların yetişkinin ricalarına ve komutlarına karşı koymalarını da beraberinde getirir. Disiplini sağlamak 2 yaşlarında oldukça önemli bir sorun haline gelir. Doğru ve yanlış kavramları, davranış kuralları, uygun tavırlar ve değerler, kendinden başka birinin bakış açısını görme yeteneği gibi, çocuğu toplumsallaşmış bir kişilik haline getiren bütün temel nitelikler, öncelikle anne baba tarafından çocuğa kazandırılır. Bu zorlu, sabır ve çaba gerektiren bir süreçtir ve gösterilen çabanın karşılığı zaman içerisinde alınır. Çocuğun uygun tavır ve davranışları gösterebilmesi için bol tekrara ve çevresindekilerin geribildirimlerine; duygusal açıdan olgunlaşabilmesi için de desteğe ve doğru yönlendirilmeye ihtiyacı vardır. 2.5 yaşından itibaren çocuk, zorlu, dikkat gerektiren ve duygu patlamaları içeren deneyimler yaşar. Bu dönemde öfke nöbetlerine sıklıkla rastlanır. Çocuk istediğini ısrarla elde etmeye, güçlü arzularına ulaşmaya, dürtülerini tatmin etmeye çalışır. İstediği her şeyi ağlayarak, vurarak, tekmeleyerek elde etme çabası içine girer. Onun emredici ve talepkar görüntüsü, kötülük olsun diye değil, kendine olan güvensizliğinden kaynaklanmaktadır. Dünya ona büyük ve tehlikeli görünür. Aslında problem kendi istekleri yerine gelmediği için öfkelenip sakinleşememesidir. Bu yüzden odadan dışarı çıkıp öfkesi dininceye kadar onu yalnız bırakmak, o anda minimum ilgi göstermek, onu ikna etme çabasına girmemek, daha sonra sakinleştiğinde yanına gitmek ve bir süre mesafeli davranmak daha doğrudur. 2 yaşındaki çocuğa bir şeyi yapmasını söylediğimizde ya bizi görmezden gelir ya da “hayır” der. Her iki durumda da yasaklanan işi yapmaya devam eder. Söyleneni yapması için kısa, açık ve net talimata, kararlı tutuma zaman zaman da fiziksel müdahaleye ihtiyacı vardır. Sadece sözel talimat uygun davranması için yeterli olmadığında, yanına gidip göz teması kurularak ciddiyetin belirtilmesi ve davranışı sonlandırması için müdahale edilmesi daha uygundur. Bu yaş çocuğunun hayal ile gerçeği ayırmada sorunu vardır. O kurduğu hayalleri, canlandırdığı öyküleri gerçek olarak algılar. Rüyalar gerçek görünmektedir, canavarlar gerçekten yatağın altında yaşıyor gibidir. Çevreden yapılan korkutucu uyaranları gerçek olarak değerlendirir.',
  '\n3 yaş çocuğun giderek daha az bencil ve annesine daha az bağımlı olduğu, daha olumlu ve dengeli bir birey haline dönüştüğü, yoğun olarak sorular sorduğu bir dönemdir. 2 yaşında başlayan sorgu çağı artarak sürmektedir. Bu yaş çocuğu, annesine ev işlerinde yardımcı olur, onunla alışverişe gider, oyun oynar, kısaca onu memnun etmeye çalışır. Bu yaş, çocuğun yaşıtlarıyla birlikte oynamaya başladığı yaştır. Yaşıtlarıyla oynamaktan mutlu olur, zamanını onlarla paylaşır. Bu tür fırsatların yaratılması onun gelecekteki sosyal uyumu açısından önemlidir. Öfke ve kırıklığını hala fiziki olarak yansıtır. Hayalle gerçeği birbirinden ayırmaya başladığı bu dönemde, hayal gücüne bağlı deneyimler yaşar. Kendi kontrolünde hayali bir arkadaş edinir. 3 yaş çocuğu diğerlerinin duygularına duyarlılık gösterir ve onların bulunduğu durumu anlayabilir. 3 yaş çocuğunun daha güçlü bir benlik duygusu vardır ve bağımsızlığı kaybetme endişesi olmaksızın itaat etme eğilimindedir. Çünkü 3 yaş çocuğu kurallara uymaktan hoşlanır. Onun olumlu davranışlarının takdir edilmesi, zorlandığı durumlarda cesaretlendirilmesi ve pozitif yaklaşımla yönlendirilmesi, yetişkinle işbirliğine girmesine yardımcı olacaktır. Anne baba olarak, empatik yaklaşarak onu anlamaya çalışmanız ve duygularını kabul etmeniz, yanında kendisini ifade edebileceği bir oyun ortamı oluşturmanız, birlikte vakit geçirebileceği oyun arkadaşı bulmanız, onu farklı sosyal ortamlara girmeye farklı kişilerle iletişim kurmaya özendirmeniz, kendine güveninin desteklenmesi açısından yararlı olacaktır',
  '\nKarşı gelme yaşıdır. Çocuk isteklerine karşı gelindiğinde, yetişkinlerle uygunsuzca, az çok kaba bir uslupla konuşabilir ve oyun arkadaşlarıyla kavga edebilir. Sınırları zorlar, yetişkin otoritesine meydan okur. Tahrik edildiğinde vurur, tekme atar, mutlu olmadığında bulunduğu ortamı terk etmek ister. Şamatalı güler, yüksek sesle ağlar, duygularında uç noktalarda dolaşan bir değişkenlik görülür. Kaba sözcükler kullanmaktan hoşlanır. 4 yaşındaki çocuk özellikle aynı cinsten olan aile bireyiyle çatışma yaşar. Bu yaş çocuğuna, doğru ve yanlış kavramları verilmeye başlanmalıdır. Gerektiğinde kendi odasına göndermek veya bir tv programı seyretmesini engellemek gibi basit cezalar uygulanabilir. Ancak, çocuğun niçin ceza aldığını bilmesi gerekir. Çünkü cezalandırılmasının sebebini merak eder ve bu açıklanmazsa kendisine haksızlık yapıldığını düşünebilir',
  '\n5 yaş çocuğu, kendi kendine yeter, sosyaldir, kendinden emindir, şekilci ve uyumludur. Uyumsuzluk ve huysuzluk dönemini geride bırakmıştır. O, kas hakimiyetinin gelişmesiyle, daha çabuk karar verebilmesiyle, düzenli cümleleriyle, insanlarla olan sosyal ilişkilerinin artmasıyla farklı bir görünüm sergiler. Anne, 5 yaş çocuğu için dünyanın merkezidir. Annesini memnun etmek, onun yanında olmak, ona yardımcı olmak ister. 5 yaş çocuğu, artık daha çabuk hareket eder. Hep konuşmak ister, yetişkinler gibi uzun cümleler kurmaya çalışır. Bilgisini arttırmak için sorular sorar, her şeyin neden ve niçini ile ilgilenir. Rahat ve ciddidir, dikkatli ve kararlıdır. Nazik bir dosttur. Olumlu geribildirime daha iyi tepki verir. 5.5 yaşına geldiğinde ise zaman zaman öfke nöbetleri ve somurtma tepkileri görülür. Çok yorulduğunda saldırgan davranır, ağlamaklı olur, kolayca ağlayabilir. Baş ağrısı, soğuk algınlığı ve karın ağrısından sıkça şikayet eder olmuştur. “Beni seviyor musunuz?” sorusunu sıkça sorar ve yanıt bekler. Anne baba çocuğu başka çocukların önünde utandırmamaya, başkalarının yanında terbiye etmemeye özen göstermelidir. 5 yaşında çocuk, kendi duygu ve düşüncelerini ortaya koyacak girişimlerde bulunur. En sevdiği şey, insan figürü çizmektir.',
  '\n1.yaş - https://www.unibaby.com.tr/faydali-bilgiler/1-2-yas-arasi-bebeklerde-zihinsel-gelisim/ \n 2.,3.,4.,5.yaş- İvet ALBUKREK, Uzman Psikolojik Danışman - https://www.ekipnormarazon.com/makalelerimiz/egitim/okul-oncesi-cocugun-psikolojik-gelisimi/'
];

List<String> oyunListHeader = [
  'Rubik Zeka Küpü',
  'Tangram',
  'Katamino',
  'Çılgın Çubuklar',
  'Hanoi Kuleleri Oyunu',
  'Sun and Moon (Gece-Gündüz) Oyunu',
  'Kelime Avı Oyunu',
  'Kaynakça'
];
List<String> oyunList = [
  '\nDiğer bir adıyla sabır küpü, 6 farklı renkten oluşan ve aynı renk küpleri aynı yüzeyde birleştirmeyi gerektiren mekanik zeka oyunudur. 3+ yaş için uygun olan bu oyuncak özellikle 5 yaş ve üzeri için tavsiye edilmektedir. Bunun sebebi, 3-4 yaşındaki çocukların ilgisini çekecek basitlikte olmayışıdır. Yine de daha küçük yaştaki çocuklarınız ilgilenecek olursa (sıkılmazsa) oynamasının hiçbir sakıncası yoktur. Rubik zeka küpü ile oynayan çocuğunuzu takip ederseniz oyunu kaç saniyede bitirdiğini not etmelisiniz. Bir sonraki denemesi ve daha sonraki denemelerinde bu süreyi kısaltmak için çabaladıkça çocuğunuzun hızlı karar verme mekanizması gelişecektir. Bununla birlikte çocuğunuzun el-göz koordinasyonu güçlenir.',
  '\n7 adet geometrik parçadan oluşan versiyonu oyun-oyuncak kategorisinde efsaneleşmiş olsa da 7’den fazla parçadan oluşan tangram oyun setleri de üretilmiştir. Geometrik parçaları farklı şekillerde bir araya getirerek yüzlerce objenin gölge görünümünü tasarlayabilirsiniz. Tangram oyunu almaya karar verirseniz kutu içeriğinde örnek görsellerin olmasına dikkat edin. Aksi halde çocuğunuzun sadece hayal gücünü geliştirecektir. Örnek görsellere bakarak aynısını yapmaya çalıştığında ise görsel zeka ve dikkat gelişimi sağlar. Hatta unutkanlığı önlemeye yönelik faydası da vardır. Tangram oyununun ahşap, plastik veya kağıt malzemeden üretilmiş modelleri mevcuttur. 5 yaşa göre oyunlar arasından tangram gibi eğlenceli oyunlar, zekanın eğitilmesinde, yani bilişsel becerilerin geliştirilmesinde oldukça etkili oyunlardır.',
  '\nPentamino adı verilen parçalardan oluşan bir zeka oyunudur. Pentaminolar, tetris oyunundaki parçalara benzer. Bu parçaları bir araya getirerek çeşitli şekiller tasarlamaya yöneliktir. Sadece 5 yaş çocuklar değil, 3+ yaşta her çocuk için ve hatta yetişkinler için de eğlenceli bir oyundur. 5 yaş zeka oyunları arasında tavsiye etmemizin sebebi ise artık çocuğunuzun oyunu daha rahat yorumlama yaşının gelmiş olmasıdır. Katamino oyunu çocuklarda analitik düşünme becerileri kazandırır. Görsel zeka gelişimi ve konsantrasyon yeteneği gelişimi de sağlar. 5 yaş oyunları eğitici oyunlardır. Katamino, okul öncesi eğitim kurumlarının da sık tercih ettiği bir oyuncaktır.',
  '\nMisketlerin altına ızgara şeklinde karşılıklı ve karışık bir şekilde dizilmiş çubukları sırayla çekerken misketleri ızgaraların arasından düşürmemeye dayalı bir oyundur. En çok misketi düşüren oyunu kaybeder. 2 veya daha fazla kişi ile oynanan bu oyun teknik olarak zor olmadığı için daha küçük yaştaki çocuklar için de uygun görülebilir ANCAK! Çubuklar 5 yaş altı çocuklarda tehlikeli bir oyun aracı olabileceği için tavsiye edilmez. 5 yaş zeka oyunları arasında iyi bir alternatif olarak kullanmaya başlayabilirsiniz. Dikkat ve konsantrasyon gerektiren bir oyundur.',
  '\nBasit kuralları olan fakat göründüğü kadar basit olmayan matematiksel zeka oyunudur. 3 kule ve 8 diskten oluşur. Her hamlede yalnızca 1 disk hareket ettirilir ve büyük disk küçük diskin üzerine konulamaz. Ters huni şeklinde yapıyı bir kuleden başka kuleye taşımayı gerektirir. Toplam hamle sayısı başarı derecesi faktörüdür. Hanoi Kuleleri, 5 yaş oyunları okul öncesi kategorisinde sıklıkla tercih edilen bir oyuncaktır.',
  '\nZeka oyunları arasında 2 yaşından 6 yaşına kadar uygun olan bu oyuncak ile çocuklar, örnek kitapçığındaki şekilleri sırıklara geçirerek oluşturmaya çalışır. Dolayısıyla ilk koyulan parça ile son koyulacak parçanın hesaplanması gerekir ki arada kalması gereken parçalar oyun dışında kalmasın. Çocuklar bu sıralamayı takip etmeye çalışırken zamanla yarışır. Problem çözme, görsel zeka ve mantık kurabilme yeteneği sağlar.',
  '\n5 yaş çocuklar için zorlayıcı ama bir o kadar da eğitici oyun olan kelime avını oynamaya başlayabilirsiniz. Kelime avı oyunu herhangi bir materyal gerektirmez. İki kişi veya daha fazla kişiyle oynanabilir. Çocuğunuza bir ses öbeği verin. Örnek: “A” ve “R” harflerinin yan yana gelmesiyle oluşan “AR” sesi. Sonra bir dakikalık süre belirleyin. Acaba, bir dakika içerisinde “Ar” ile başlayan kaç kelime bulabileceksiniz? Arkadaş, araba, arma, arı… En çok kelimeyi bulan oyunu kazanır.  Yetişkin olarak, çocuğunuzu yenecek olmanız olasıdır. Dolayısıyla, onun motivasyonunu artırmak için çok fazla kelime bulamamış gibi davranabilirsiniz. Oyunda birden fazla çocuk varsa çok daha eğlenceli ve rekabetli olacaktır. Kelime avı oyunu, çocukların kelime haznesini geliştiren mükemmel bir oyundur. Anaokullarında 5 yaş eğitici oyunlar oynatılırken sık sık tercih edilir.',
  '\nTüm oyunların kaynakçası - Bünyamin Kapıcıoğlu - https://www.mentalup.net/blog/5-yas-zeka-oyunlari'
];

List<String> dogaListHeader = [
  '200 Yıllık Eğitimine Alternatif Çözüm',
  'Anne ve Babaların Ekoloji Eğitimdeki Rolü',
  'Siz Çocuğunuzla Neler Yapabilirsiniz?',
  'Kaynakça'
];
List<String> dogaList = [
  '\nEkoloji EğitimiOkul öncesi ve okul çağı dönemi, çocukların bilgi ve becerilerinin temellerinin aldığı dönemdir. Bebekler dünyaya geldiklerinde çevrelerini duyuları yoluyla tanımaya ve keşfetmeye başlar. Bebekler için her şey merak konusudur ve bu merakları onları çevrelerini incelemeye ve araştırmaya yönelir. Örneğin, bebek eline aldığı bir nesneye bakar, ona dokunur, sesini dinler ve ağzına götürür. Yürümeye başladıklarında ise ark çocuklar çevrelerini rahatça araştırmaya başlar. Ekoloji temelli eğimin en önemli eğim aracı “doğa”dır. Doğa’da bulunan her canlı ve cansız obje çocuk eğiminde duyusal, bilişsel ve fiziksel eğimin bir parçasıdır. Çocuklar çiçekleri, yaprakları ve çeşitli kabukları toplamaktan hoşlanır, yakın çevrelerindeki hayvanların hareketleri onların ilgisini çeker. Böylece bu dönemde çocuklar fen ve doğa etkinlikleriyle ilgili ilk deneyimlerini kazanmaya başlar. Özellikle "çevrelerindeki gözlemleri sonucu suyun üstünde neler durur, neler batar, böcek zemin üzerinde nasıl yürür, herhangi bir yüzeye nasıl tırmanır?" gibi sorulara cevap arar, tahminlerde bulunur ve araştırırlar. Küçük çocuklar çevrelerini araştırır, geçirdikleri bazı yaşantılar sonucu bilgiler edinir ve böylece yeni şeyleri öğrenmek için bir temel oluştururlar.',
  '\nDoğa etkinliklerinde anne ve babaların rolü önemlidir. Anne ve babalar bilime karşı meraklı, olumlu tutum içinde birer kişiliğe sahip olmalıdır. Çocuklara kalıp bilgi vermek yerine zengin bir ortam hazırlamalıdır. Uygulamalar esnasında çocukları ile iletişim içinde olmalı, her çocuğun etkinliğe aktif olarak katılmasını sağlamalıdır. Çocuklara, doğa etkinlikleri ile ilgili sorular sormaları için ortam hazırlamalıdır. Çocukların sorularını yanıtsız bırakmamalı, doğru yanıtlar vermeli ya da birlikte bulmaya çalışmalıdır. Bu etkinlikler esnasında ebeveynler çocuklarla beraber araştırır; onlarla beraber gözler ve inceler. Toplanan yaprak, çiçek, taş, deniz kabukları ev içerisinde belirli alanlarda sergilenmeli; bazı hayvanlar evde beslenmeli çocuklarla beraber hava ve mevsim değişmeleri gözlemlenmelidir. Bazen ebeveynlerin çocuklara sorular sorması, onların düşüncelerini açığa kavuşturmasını sağlamalıdır.',
  '\nEvinizde bir “harikalar sandığı” olsun ve her bulduğunuzu içine atın, özelliklerini keşfedin, latince isimlerini öğrenin. Bir doğa günlüğü tutun, her günün bir resmini çizin ve bir sonraki gün için hayal kurun.  Bir ağacı evlat edinin ya da aileniz için bir ağaç dikin, ona her gün sarılın. Evinizde geri dönüşüm seferberliği başlatın. Yeniden kullanılabilir cam, metal, kağıt, plastik gibi materyalleri ayrı ayrı biriktirin ve geri dönüşüm kutularına atın. Bir sebze bahçesi oluşturun. Hasada gidin. Kuş gözlemcisi olun. Taş toplayın. En küçük çocuklar bile taş, kabuk ve fosil toplamayı sever. Yerli bitki ve hayvanları yaşamınıza dahil edin. Bahçenizde ya da balkonunuzda yerli bitkiler yetiştirin ve onların bakımını yaparken çocuklarınız ile birlikte hareket edin.',
  '\nTüm yazıların kaynakçası - Merve TOPÇUOĞLU - http://apelasyon.com/Yazi/625-ekoloji-temelli-egitim-ekolojik-okur-yazarlik'
];

List<String> ingilizceListHeader = [
  'Erken yaşta yabancı dil eğitimi zararlı mı?',
  'Peki yabancı dil eğitimine kaç yaşında başlanmalı?',
  'İkinci dil öğretimindeki kritik dönem',
  'Yabancı dil eğitiminde öğretmen nasıl olmalıdır?',
  'Çocuğa yabancı dil eğitimi verilirken unutulmaması gerekenler',
  'Kaynakça'
];
List<String> ingilizceList = [
  '\nGeçmiş yıllarda erken yaşta yabancı dil eğitimi alan çocukların ana dillerinde bozulmalar olduğu ile ilgili görüşler karşımıza çıkmaktaydı. Ancak son dönemlerde yabancı dile eğitimi ile ilgili yapılan araştırmalar, çocukların erken yaşta yabancı dil öğrenmelerinin ana dillerini etkilemediği aksine erken yaşta yabancı dil öğrenmenin faydaları olduğu, çocukların bilişsel gelişimlerini ve akademik başarılarını arttırdığını, bir göreve odaklanmaları kolaylaştırdığını ortaya koymaktadır.',
  '\nUzmanlara göre küçük yaşta ikinci dil öğretimine başlandığında öğrenme daha kalıcı hale gelmektedir. Çocukların yabancı dil öğrenmesi üzerine yapılan bilimsel çalışmalar yabancı dil öğrenme yaşının 3-4 yaş olduğunu göstermektedir. Bu dönemde dil öğrenimi doğal bir biçimde gerçekleşmektedir. Ana dil gelişiminin ilk işaretleri 12 ay civarında görülmektedir. Bu dönemde çocuklar tek tek öğrendikleri kelimeleri söylemeye, isteklerini kelimeler yoluyla ifade etmeye başlamışlardır. Zamanla öğrendikleri kelimelerdeki artış ve ana dilin gramer yapısını anlamaları ile birlikte 3 yaşına kadar cümleler kurmaya, çevresinde olan biteni kendi bakış açısı ile ifade etmeye başlar. Bu süreçlerden normal bir gelişim seyri ile geçen her çocuk için 3-4 yaşları ikinci yabacı dil eğitimine başlamak uygun olacaktır.',
  '\nÇocuklarda yabancı dil eğitiminde en kazançlı dönem 2-7 yaşları arasıdır. Ancak bu sonraki dönemlerde yabancı dil öğrenilemeyecek olması anlamına gelmemektedir. Bu dönemde çocukların öğrenme hızı fazla olduğu için dil öğrenimi doğal ve kolay olarak gerçekleşecektir. Beyin gelişiminde en kritik dönemler 0-5 yaş ve sonrada ergenlik dönemidir. Bu durum dil öğrenimi içinde geçerlidir. Ergenlik döneminden sonra yabancı dil öğrenmek zorlaşmaktadır. Dil öğrenimine ne kadar erken başlanırsa kalıcılığında o kadar fazla olacağı unutulmamalıdır',
  '\nKüçük yaş grubundaki çocuklara yabancı dil eğitimi verilirken öncelikle eğitimcilerin bu konuda eğitim almış, çocuk gelişim ve psikolojisinden anlayan, çocukların nasıl dil öğrendiğini bilen kişiler olmasına dikkat edilmelidir. Çocukların yabancı dil öğrenme süreci ana dil gibi işler, önce tek tek öğrendikleri kelimeleri taklit ederler, daha sonra uygun yerlerde kullanırlar, zamanla kelimeleri yan yana getirerek basit cümleler kurmaya başlarlar. Dil öğreniminde dili anlama, konuşmadan daha önce gelişir. Çocuklar önce yabancı dili anlamaya sonrada konuşmaya başlarlar. Bu sebeple ne kadar çok yabancı dile maruz kalırlarsa o kadar çabuk öğrenme gerçekleşecektir. Oyun ve şarkılar yolu ile yapılacak yabacı dil öğretimi hem çocukların keyif almasını hem de doğal yolla yabancı dil edinimini sağlayacaktır.',
  '\nOkul öncesi dönemde çocuğunuzun yabancı dil öğrenmesi bilişsel gelişimi için önemlidir. Ancak unutulmamalıdır ki çocuğunuz 0-2 yaş döneminde, en çok anne-babalarının sevgilerine ve ilgilerine ihtiyaç duymaktadır. Bu dönemlerde yabancı dil öğretmek konusunda göstereceğiniz zorlamalar, çocuğunuzun hem duygusal gelişimini hem de dil edinim sürecini olumsuz etkileyebilir. Böyle bir durum ile karşılaştığınızda bir uzman desteği almanız faydalı olacaktır.',
  '\nTüm yazıların kaynakçası - Elif Biçer - https://okul.com.tr/aileler-icin/makaleleri/erken-yasta-dil-egitimi-26'
];

List<String> hakkimizdaListHeader = [
  'Biz Kimiz?',
  'Amacımız',
];
List<String> hakkimizdaList = [
  'EMI MOON',
  'İyilik',
];
